### ISSUE TITLE
Rom Loading / Fullscreen / Chromebook

### ISSUE THREAD

**Issue by hpkoopmann** [mattgodbolt/Miracle#3]
Hello.
I tried to use the Miracle with Googles Chromebook.
It worked so far, but i faced the following problems:

- Is it possible to get Fullscreen Support?
- I have *.sms Roms here, and i chose the file to load. Nothing happens
  How do i load custom roms directly in the browser?

HP

**Comment by mattgodbolt** [comment]
Fullscreen: I can definitely take this as a TODO
The SMS rom loading support is broken (whoops!) - I'll try and get it fixed!

**Comment by mattgodbolt** [comment]
(Separating into two bugs) #4 and #5
